#!/usr/bin/env bash

[ "$TRACE" == "true" ] && set -x
set -e
set -o pipefail

DEST_DIR="$1"

GIT_DEST_DIR="$(mktemp -d -t git-resource-destination.XXXXXX)"

/opt/resource/git/in "$GIT_DEST_DIR"

payload=$(echo /tmp/git-resource-request.*)

registry=$(jq -r '.source.registry // ""' < $payload)
token=$(jq -r '.source.token // ""' < $payload)

cd "$GIT_DEST_DIR"

if [  "$http_proxy" != "" ]; then

    echo "Set npm httproxy: "$http_proxy"" >&2

    npm config set proxy $http_proxy
    npm config set https-proxy $https_proxy
fi

if [  "$token" != "" ]; then

    echo "Set token in our .npmrc file: "$token"" >&2

    echo "always-auth=true" >> ~/.npmrc
    echo "_auth="$token"" >> ~/.npmrc

    cat ~/.npmrc >&2
fi

if [  "$registry" != "" ]; then

    echo "Set Private Registry: "$registry"" >&2
    npm config set registry $registry
fi

NODE_ENV=development && npm install --quiet  >&2

cp -R node_modules "$DEST_DIR/"